name: Android Debug build

on:
  push:
    branches:
      - dev-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          add-job-summary-as-pr-comment: on-failure # Valid values are 'never' (default), 'always', and 'on-failure'
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Setup keystore
        run: |
          echo "${{secrets.KEYSTORE}}" > keystore.jks.asc
          gpg -d --batch --passphrase "${{secrets.GPG_PASS}}" --output app/keystore.jks keystore.jks.asc

      - name: Build App
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug \
              -Pkeystore=keystore.jks \
              -Pstorepass=${{secrets.STORE_PASS}} \
              -Pkeypass=${{secrets.KEY_PASS}} \
              -Pkeyalias=${{secrets.KEY_NAME}}

      - name: Delete keystore
        run: rm -f keystore.jks keystore.jks.asc

      - name: Archive APK
        uses: actions/upload-artifact@v4
        with:
          name: Quillpad Debug APKs
          path: |
            app/build/outputs/apk/defaultFlavor/debug/app-defaultFlavor-debug.apk
            app/build/outputs/apk/googleFlavor/debug/app-googleFlavor-debug.apk

